// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:simple_player/models/playlist.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PlaylistAdapter());
    registerAdapter(SongMetadataAdapter());
  }
}
